import { Base } from "./Base";

export class Address extends Base {
  static className: string = "Address";

  constructor() {
    super();
    this._fields = [
      {
        name: "@id",
        type: "string",
        representedType: "string",
        primary: true,
        unique: true,
        notNull: true,
        required: true,
        semiRequired: false,
      },
      {
        name: "ic:hasStreet",
        displayName: "hasStreet",
        type: "text",
        representedType: "string",
        defaultValue: "",
        unique: false,
        notNull: false,
        required: false,
        semiRequired: false,
      },
      {
        name: "ic:hasStreetType",
        displayName: "hasStreetType",
        type: "select",
        selectOptions: [
          { id: "ic:avenue", name: "Avenue" },
          { id: "ic:boulevard", name: "Boulevard" },
          { id: "ic:circle", name: "Circle" },
          { id: "ic:crescent", name: "Crescent" },
          { id: "ic:drive", name: "Drive" },
          { id: "ic:road", name: "Road" },
          { id: "ic:street", name: "Street" },
        ],
        representedType: "string",
        defaultValue: "",
        unique: false,
        notNull: false,
        required: false,
        semiRequired: false,
      },
      {
        name: "ic:hasStreetNumber",
        displayName: "hasStreetNumber",
        type: "string",
        representedType: "string",
        defaultValue: "",
        unique: false,
        notNull: false,
        required: false,
        semiRequired: false,
      },
      {
        name: "ic:hasStreetDirection",
        displayName: "hasStreetDirection",
        type: "select",
        selectOptions: [
          { id: "ic:north", name: "North" },
          { id: "ic:east", name: "East" },
          { id: "ic:south", name: "South" },
          { id: "ic:west", name: "West" },
        ],
        representedType: "string",
        defaultValue: "",
        unique: false,
        notNull: false,
        required: false,
        semiRequired: false,
      },
      {
        name: "ic:hasUnitNumber",
        displayName: "hasUnitNumber",
        type: "string",
        representedType: "string",
        defaultValue: "",
        unique: false,
        notNull: false,
        required: false,
        semiRequired: false,
      },
      {
        name: "ic:hasCity",
        displayName: "hasCity",
        type: "string",
        representedType: "string",
        defaultValue: "",
        unique: false,
        notNull: false,
        required: false,
        semiRequired: false,
      },
      {
        name: "ic:hasState",
        displayName: "hasState",
        type: "string",
        representedType: "string",
        defaultValue: "",
        unique: false,
        notNull: false,
        required: false,
        semiRequired: false,
      },
      {
        name: "ic:hasPostalCode",
        displayName: "hasPostalCode",
        type: "string",
        representedType: "string",
        defaultValue: "",
        unique: false,
        notNull: false,
        required: false,
        semiRequired: false,
      },
      {
        name: "ic:hasCountry",
        displayName: "hasCountry",
        type: "string",
        representedType: "string",
        defaultValue: "",
        unique: false,
        notNull: false,
        required: false,
        semiRequired: false,
      },
    ];
  }
}
